baseURL: https://joshuawillems.netlify.app/
languageCode: en-US
title: Joshua Willems
theme: hugo-split-theme
disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap
relativeURLs: yes
uglyURLs: yes
googleAnalytics: ''
copyright: '&copy;2021 Joshua Willems'
params:
  author: Joshua Willems
  description: Split is a centrally-divided layout for a professional online presence
    with a big image or video left with alongside content.
  links:
    - list1:
        heading: Pages
        link:
          - text: Research
            url: 'C:\Users\jswil\Documents\R\Website\content\ipsum-in.md'
          - text: CV
            url: 'luctus-uma.md'
    - list2:
        heading: Social
        link:
          - text: Twitter
            url: 'https://twitter.com/JoshuaWillems2'
          - text: Google Scholar
            url: 'https://scholar.google.com/citations?user=mX4XW5MAAAAJ&hl=en'
          - text: GitHub
            url: 'https://github.com/jwillems92'
  shareImage: images/social.jpg
  twitterHandle: onepagelove
  visual:
    image:
      enable: yes
      file: images/Photo1.jpg
      position: center center
    video:
      enable: no
      file: videos/background.mp4
      mute: yes
